import {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "es" | "pt";

type TranslationKey = keyof typeof translations.es;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
  locale: string;
}

const translations = {
  es: {
    appName: "Soporte Técnico",
    embassy: "Embaixada do Brasil",
    consularSystem: "Sistema de Gestión Consular",
    dashboard: "Dashboard",
    tickets: "Tickets",
    myTicketStatus: "Estado de mis tickets",
    assets: "Activos",
    network: "Red",
    telephony: "Telefonía",
    maintenance: "Mantenimiento",
    reports: "Reportes",
    users: "Usuarios",
    audit: "Auditoría",
    admin: "Administrador",
    technician: "Técnico",
    user: "Usuario",
    languageToggle: "PT",
    languageLabel: "Português",
    selectLanguage: "Selecciona tu idioma",
    emailOrCpf: "Email",
    emailPlaceholder: "tu.email@ejemplo.com",
    password: "Contraseña",
    rememberMe: "Recordarme",
    accessRequestTitle: "Solicitar acceso",
    accessRequestIntro: "Envía tus datos al administrador para que pueda crear tu usuario.",
    fullName: "Nombre completo",
    workArea: "Área o dependencia",
    phone: "Teléfono",
    message: "Mensaje",
    accessReason: "Explica por qué necesitas acceso al sistema",
    sendToAdmin: "Enviar al administrador",
    sendingRequest: "Enviando solicitud...",
    adminAccessRequestSent: "Solicitud enviada al administrador",
    adminAccessRequestNote: "Tu solicitud fue registrada. El administrador revisará la información y se comunicará contigo.",
    login: "Entrar",
    loggingIn: "Ingresando...",
    loginFailed: "Error al iniciar sesión",
    or: "o",
    govAccess: "Acceso con Gov.br",
    digitalCertificate: "Certificado Digital",
    noAccount: "¿No tienes una cuenta?",
    requestAccess: "Solicitar acceso",
    total: "Total",
    openTickets: "Tickets Abiertos",
    closedTickets: "Tickets Cerrados",
    registeredAssets: "Equipos Registrados",
    activeAssets: "activos",
    pendingMaintenance: "Mantenimientos Pendientes",
    overdue: "vencidos",
    ticketsByPriority: "Tickets por Prioridad",
    assetsByType: "Equipos por Tipo",
    low: "Baja",
    medium: "Media",
    high: "Alta",
    critical: "Crítica",
    pending: "Pendiente",
    open: "Abierto",
    pendingAssignment: "Pendiente de asignación",
    assignedStatus: "Asignado",
    inProgress: "En Proceso",
    onHold: "En espera",
    resolved: "Resuelto",
    finalized: "Finalizado",
    closed: "Cerrado",
    canceled: "Cancelado",
    undefinedPriority: "Por definir",
    available: "Disponible",
    active: "Activo",
    inactive: "Inactivo",
    faulty: "Dañado",
    maintenanceStatus: "En Mantenimiento",
    disposed: "Dado de Baja",
    preventive: "Preventivo",
    corrective: "Correctivo",
    assigned: "Asignados",
    assignedTickets: "Mis Tickets Asignados",
    technicianPanel: "Panel del Técnico",
    userPanel: "Panel de Usuario",
    supportRequest: "Nueva Solicitud de Soporte",
    recentRequests: "Mis Solicitudes Recientes",
    myRequests: "Mis Solicitudes",
    viewAll: "Ver todas",
    noRequests: "No has realizado ninguna solicitud aún.",
    pendingTickets: "Tickets Pendientes",
    noPendingTickets: "No tienes tickets pendientes.",
    noInProgressTickets: "No tienes tickets en proceso.",
    title: "Título",
    description: "Descripción",
    priority: "Prioridad",
    status: "Estado",
    sendRequest: "Enviar Solicitud",
    sending: "Enviando...",
    save: "Guardar",
    saving: "Guardando...",
    create: "Crear",
    update: "Actualizar",
    cancel: "Cancelar",
    close: "Cerrar",
    delete: "Eliminar",
    refresh: "Actualizar",
    search: "Buscar...",
    searchTickets: "Buscar tickets...",
    searchAssets: "Buscar activos...",
    searchNetwork: "Buscar puntos...",
    searchExtensions: "Buscar extensiones...",
    searchUsers: "Buscar usuarios...",
    all: "Todos",
    allStatuses: "Todos los estados",
    allTypes: "Todos los tipos",
    allPriorities: "Todas las prioridades",
    allRoles: "Todos",
    noTicketsFound: "No se encontraron tickets",
    newTicket: "Nuevo Ticket",
    editTicket: "Editar Ticket",
    noAssetsFound: "No se encontraron activos",
    noNetworkFound: "No se encontraron puntos de red",
    noExtensionsFound: "No se encontraron extensiones",
    noMaintenanceFound: "No se encontraron registros",
    noUsersFound: "No se encontraron usuarios",
    page: "Página",
    of: "de",
    computerAssets: "Activos Informáticos",
    newAsset: "Nuevo Activo",
    editAsset: "Editar Activo",
    code: "Código",
    internalCode: "Código Interno",
    type: "Tipo",
    brand: "Marca",
    model: "Modelo",
    serial: "N° Serie",
    assignedTo: "Asignado a",
    location: "Ubicación",
    acquisitionDate: "Fecha Adquisición",
    observations: "Observaciones",
    computer: "Computadora",
    laptop: "Laptop",
    printer: "Impresora",
    ups: "UPS",
    switch: "Switch",
    router: "Router",
    ipPhone: "Teléfono IP",
    monitor: "Monitor",
    other: "Otro",
    networkInfrastructure: "Infraestructura de Red",
    newNetworkPoint: "Nuevo Punto",
    editNetworkPoint: "Editar Punto de Red",
    label: "Etiqueta",
    patchPanel: "Patch Panel",
    switchPort: "Puerto Switch",
    extension: "Extensión",
    newExtension: "Nueva Extensión",
    editExtension: "Editar Extensión",
    extensionNumber: "Número de Extensión",
    ipAddress: "Dirección IP",
    maintenanceTitle: "Mantenimiento",
    newMaintenance: "Nuevo Mantenimiento",
    editMaintenance: "Editar Mantenimiento",
    equipment: "Equipo",
    scheduled: "Programado",
    performed: "Realizado",
    nextMaintenance: "Próximo",
    assetId: "ID del Activo",
    scheduledDate: "Fecha Programada",
    performedDate: "Fecha Realizada",
    nextMaintenanceDate: "Próximo Mantenimiento",
    name: "Nombre",
    role: "Rol",
    enabled: "Activo",
    yes: "Sí",
    no: "No",
    created: "Creado",
    newUser: "Nuevo Usuario",
    editUser: "Editar Usuario",
    keepPassword: "(dejar vacío para mantener)",
    deleteUserConfirm: "¿Eliminar usuario",
    ticketCreated: "Ticket creado",
    ticketUpdated: "Ticket actualizado",
    ticketSavedError: "Error al guardar el ticket",
    requestSent: "Solicitud enviada correctamente",
    requestError: "Error al enviar la solicitud",
    assetCreated: "Activo creado",
    assetUpdated: "Activo actualizado",
    networkCreated: "Punto de red creado",
    networkUpdated: "Punto de red actualizado",
    extensionCreated: "Extensión creada",
    extensionUpdated: "Extensión actualizada",
    maintenanceCreated: "Mantenimiento registrado",
    maintenanceUpdated: "Mantenimiento actualizado",
    userCreated: "Usuario creado",
    userUpdated: "Usuario actualizado",
    userDeleted: "Usuario eliminado",
    genericError: "Error",
    backToTickets: "Volver a Tickets",
    ticketNotFound: "Ticket no encontrado",
    requester: "Solicitante",
    assignedTechnician: "Técnico Asignado",
    lastUpdate: "Última Actualización",
    resolution: "Resolución",
    comments: "Comentarios",
    timeline: "Línea de tiempo",
    noComments: "No hay comentarios aún.",
    addComment: "Añadir un comentario...",
    send: "Enviar",
    changeHistory: "Historial de Cambios",
    noHistory: "No hay historial.",
    changed: "cambió",
    from: "de",
    to: "a",
    commentAdded: "Comentario agregado",
    commentError: "Error al agregar comentario",
    ticketLoadError: "Error al cargar ticket",
    withoutAssignment: "Sin asignar",
    monthlyReportError: "Error al generar reporte mensual",
    authProblemPlaceholder: "Describe brevemente tu problema",
    detailedProblemPlaceholder:
      "Explica detalladamente el problema que estás experimentando...",
    problemPlaceholder: "Explica detalladamente el problema...",
    computers: "Computadoras",
    printers: "Impresoras",
    networkShort: "Red",
    others: "Otros",
  },
  pt: {
    appName: "Suporte Técnico",
    embassy: "Embaixada do Brasil",
    consularSystem: "Sistema de Gestão Consular",
    dashboard: "Painel",
    tickets: "Tickets",
    myTicketStatus: "Estado dos meus tickets",
    assets: "Ativos",
    network: "Rede",
    telephony: "Telefonia",
    maintenance: "Manutenção",
    reports: "Relatórios",
    users: "Usuários",
    audit: "Auditoria",
    admin: "Administrador",
    technician: "Técnico",
    user: "Usuário",
    languageToggle: "ES",
    languageLabel: "Español",
    selectLanguage: "Selecione seu idioma",
    emailOrCpf: "Email",
    emailPlaceholder: "seu.email@exemplo.com",
    password: "Senha",
    rememberMe: "Lembrar-me",
    accessRequestTitle: "Solicitar acesso",
    accessRequestIntro: "Envie seus dados ao administrador para que possa criar seu usuário.",
    fullName: "Nome completo",
    workArea: "Área ou setor",
    phone: "Telefone",
    message: "Mensagem",
    accessReason: "Explique por que você precisa de acesso ao sistema",
    sendToAdmin: "Enviar ao administrador",
    sendingRequest: "Enviando solicitação...",
    adminAccessRequestSent: "Solicitação enviada ao administrador",
    adminAccessRequestNote: "Sua solicitação foi registrada. O administrador revisará as informações e entrará em contato.",
    login: "Entrar",
    loggingIn: "Entrando...",
    loginFailed: "Falha ao entrar",
    or: "ou",
    govAccess: "Acesso com Gov.br",
    digitalCertificate: "Certificado Digital",
    noAccount: "Não tem uma conta?",
    requestAccess: "Solicitar acesso",
    total: "Total",
    openTickets: "Tickets Abertos",
    closedTickets: "Tickets Fechados",
    registeredAssets: "Equipamentos Registrados",
    activeAssets: "ativos",
    pendingMaintenance: "Manutenções Pendentes",
    overdue: "vencidos",
    ticketsByPriority: "Tickets por Prioridade",
    assetsByType: "Equipamentos por Tipo",
    low: "Baixa",
    medium: "Média",
    high: "Alta",
    critical: "Crítica",
    pending: "Pendente",
    open: "Aberto",
    pendingAssignment: "Pendente de atribuição",
    assignedStatus: "Atribuído",
    inProgress: "Em Processo",
    onHold: "Em espera",
    resolved: "Resolvido",
    finalized: "Finalizado",
    closed: "Fechado",
    canceled: "Cancelado",
    undefinedPriority: "A definir",
    available: "Disponível",
    active: "Ativo",
    inactive: "Inativo",
    faulty: "Com Defeito",
    maintenanceStatus: "Em Manutenção",
    disposed: "Baixado",
    preventive: "Preventiva",
    corrective: "Corretiva",
    assigned: "Atribuídos",
    assignedTickets: "Meus Tickets Atribuídos",
    technicianPanel: "Painel do Técnico",
    userPanel: "Painel do Usuário",
    supportRequest: "Nova Solicitação de Suporte",
    recentRequests: "Minhas Solicitações Recentes",
    myRequests: "Minhas Solicitações",
    viewAll: "Ver todas",
    noRequests: "Você ainda não fez nenhuma solicitação.",
    pendingTickets: "Tickets Pendentes",
    noPendingTickets: "Você não tem tickets pendentes.",
    noInProgressTickets: "Você não tem tickets em processo.",
    title: "Título",
    description: "Descrição",
    priority: "Prioridade",
    status: "Estado",
    sendRequest: "Enviar Solicitação",
    sending: "Enviando...",
    save: "Salvar",
    saving: "Salvando...",
    create: "Criar",
    update: "Atualizar",
    cancel: "Cancelar",
    close: "Fechar",
    delete: "Excluir",
    refresh: "Atualizar",
    search: "Buscar...",
    searchTickets: "Buscar tickets...",
    searchAssets: "Buscar ativos...",
    searchNetwork: "Buscar pontos...",
    searchExtensions: "Buscar ramais...",
    searchUsers: "Buscar usuários...",
    all: "Todos",
    allStatuses: "Todos os estados",
    allTypes: "Todos os tipos",
    allPriorities: "Todas as prioridades",
    allRoles: "Todos",
    noTicketsFound: "Nenhum ticket encontrado",
    newTicket: "Novo Ticket",
    editTicket: "Editar Ticket",
    noAssetsFound: "Nenhum ativo encontrado",
    noNetworkFound: "Nenhum ponto de rede encontrado",
    noExtensionsFound: "Nenhum ramal encontrado",
    noMaintenanceFound: "Nenhum registro encontrado",
    noUsersFound: "Nenhum usuário encontrado",
    page: "Página",
    of: "de",
    computerAssets: "Ativos de Informática",
    newAsset: "Novo Ativo",
    editAsset: "Editar Ativo",
    code: "Código",
    internalCode: "Código Interno",
    type: "Tipo",
    brand: "Marca",
    model: "Modelo",
    serial: "N° de Série",
    assignedTo: "Atribuído a",
    location: "Localização",
    acquisitionDate: "Data de Aquisição",
    observations: "Observações",
    computer: "Computador",
    laptop: "Laptop",
    printer: "Impressora",
    ups: "UPS",
    switch: "Switch",
    router: "Roteador",
    ipPhone: "Telefone IP",
    monitor: "Monitor",
    other: "Outro",
    networkInfrastructure: "Infraestrutura de Rede",
    newNetworkPoint: "Novo Ponto",
    editNetworkPoint: "Editar Ponto de Rede",
    label: "Etiqueta",
    patchPanel: "Patch Panel",
    switchPort: "Porta do Switch",
    extension: "Ramal",
    newExtension: "Novo Ramal",
    editExtension: "Editar Ramal",
    extensionNumber: "Número do Ramal",
    ipAddress: "Endereço IP",
    maintenanceTitle: "Manutenção",
    newMaintenance: "Nova Manutenção",
    editMaintenance: "Editar Manutenção",
    equipment: "Equipamento",
    scheduled: "Agendado",
    performed: "Realizado",
    nextMaintenance: "Próxima",
    assetId: "ID do Ativo",
    scheduledDate: "Data Agendada",
    performedDate: "Data Realizada",
    nextMaintenanceDate: "Próxima Manutenção",
    name: "Nome",
    role: "Perfil",
    enabled: "Ativo",
    yes: "Sim",
    no: "Não",
    created: "Criado",
    newUser: "Novo Usuário",
    editUser: "Editar Usuário",
    keepPassword: "(deixe vazio para manter)",
    deleteUserConfirm: "Excluir usuário",
    ticketCreated: "Ticket criado",
    ticketUpdated: "Ticket atualizado",
    ticketSavedError: "Erro ao salvar o ticket",
    requestSent: "Solicitação enviada corretamente",
    requestError: "Erro ao enviar a solicitação",
    assetCreated: "Ativo criado",
    assetUpdated: "Ativo atualizado",
    networkCreated: "Ponto de rede criado",
    networkUpdated: "Ponto de rede atualizado",
    extensionCreated: "Ramal criado",
    extensionUpdated: "Ramal atualizado",
    maintenanceCreated: "Manutenção registrada",
    maintenanceUpdated: "Manutenção atualizada",
    userCreated: "Usuário criado",
    userUpdated: "Usuário atualizado",
    userDeleted: "Usuário excluído",
    genericError: "Erro",
    backToTickets: "Voltar para Tickets",
    ticketNotFound: "Ticket não encontrado",
    requester: "Solicitante",
    assignedTechnician: "Técnico Atribuído",
    lastUpdate: "Última Atualização",
    resolution: "Resolução",
    comments: "Comentários",
    timeline: "Linha do tempo",
    noComments: "Ainda não há comentários.",
    addComment: "Adicionar um comentário...",
    send: "Enviar",
    changeHistory: "Histórico de Alterações",
    noHistory: "Não há histórico.",
    changed: "alterou",
    from: "de",
    to: "para",
    commentAdded: "Comentário adicionado",
    commentError: "Erro ao adicionar comentário",
    ticketLoadError: "Erro ao carregar ticket",
    withoutAssignment: "Sem atribuição",
    monthlyReportError: "Erro ao gerar relatório mensal",
    authProblemPlaceholder: "Descreva brevemente seu problema",
    detailedProblemPlaceholder:
      "Explique detalhadamente o problema que você está enfrentando...",
    problemPlaceholder: "Explique detalhadamente o problema...",
    computers: "Computadores",
    printers: "Impressoras",
    networkShort: "Rede",
    others: "Outros",
  },
} as const;

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return saved === "pt" || saved === "es" ? saved : "es";
  });

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  const toggleLanguage = () => {
    setLanguageState((current) => (current === "es" ? "pt" : "es"));
  };

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language === "pt" ? "pt-BR" : "es";
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t: (key) => translations[language][key],
      locale: language === "pt" ? "pt-BR" : "es-ES",
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context)
    throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
